name: 应用定时管家
package: community.lazycat.app.czyt.apps-scheduler
version: 1.0.1
min_os_version: 1.5.0
description: "定时启动和停止懒猫微服上的应用"
license: mit/
homepage: https://czyt.tech
author: czyt

locales:
  zh:
    name: "应用定时管家"
    description: "定时启动和停止懒猫微服上的应用"
  en:
    name: "App Scheduler"
    description: "Schedule start and stop operations for apps on LazyCat"
  ja:
    name: "アプリスケジューラー"
    description: "LazyCat上のアプリを定期的に起動・停止"

unsupported_platforms:
  - ios
  - android
  - tvos
