// Code generated by ent, DO NOT EDIT.

package mcptoken

import (
	"apps-scheduler/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldName, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenPrefix applies equality check predicate on the "token_prefix" field. It's identical to TokenPrefixEQ.
func TokenPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenPrefix, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldUserID, v))
}

// UserRole applies equality check predicate on the "user_role" field. It's identical to UserRoleEQ.
func UserRole(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldUserRole, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldCreatedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldRevokedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldName, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// TokenPrefixEQ applies the EQ predicate on the "token_prefix" field.
func TokenPrefixEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenPrefixNEQ applies the NEQ predicate on the "token_prefix" field.
func TokenPrefixNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldTokenPrefix, v))
}

// TokenPrefixIn applies the In predicate on the "token_prefix" field.
func TokenPrefixIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldTokenPrefix, vs...))
}

// TokenPrefixNotIn applies the NotIn predicate on the "token_prefix" field.
func TokenPrefixNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldTokenPrefix, vs...))
}

// TokenPrefixGT applies the GT predicate on the "token_prefix" field.
func TokenPrefixGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldTokenPrefix, v))
}

// TokenPrefixGTE applies the GTE predicate on the "token_prefix" field.
func TokenPrefixGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldTokenPrefix, v))
}

// TokenPrefixLT applies the LT predicate on the "token_prefix" field.
func TokenPrefixLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldTokenPrefix, v))
}

// TokenPrefixLTE applies the LTE predicate on the "token_prefix" field.
func TokenPrefixLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldTokenPrefix, v))
}

// TokenPrefixContains applies the Contains predicate on the "token_prefix" field.
func TokenPrefixContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldTokenPrefix, v))
}

// TokenPrefixHasPrefix applies the HasPrefix predicate on the "token_prefix" field.
func TokenPrefixHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldTokenPrefix, v))
}

// TokenPrefixHasSuffix applies the HasSuffix predicate on the "token_prefix" field.
func TokenPrefixHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldTokenPrefix, v))
}

// TokenPrefixEqualFold applies the EqualFold predicate on the "token_prefix" field.
func TokenPrefixEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldTokenPrefix, v))
}

// TokenPrefixContainsFold applies the ContainsFold predicate on the "token_prefix" field.
func TokenPrefixContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldTokenPrefix, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldUserID, v))
}

// UserRoleEQ applies the EQ predicate on the "user_role" field.
func UserRoleEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldUserRole, v))
}

// UserRoleNEQ applies the NEQ predicate on the "user_role" field.
func UserRoleNEQ(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldUserRole, v))
}

// UserRoleIn applies the In predicate on the "user_role" field.
func UserRoleIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldUserRole, vs...))
}

// UserRoleNotIn applies the NotIn predicate on the "user_role" field.
func UserRoleNotIn(vs ...string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldUserRole, vs...))
}

// UserRoleGT applies the GT predicate on the "user_role" field.
func UserRoleGT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldUserRole, v))
}

// UserRoleGTE applies the GTE predicate on the "user_role" field.
func UserRoleGTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldUserRole, v))
}

// UserRoleLT applies the LT predicate on the "user_role" field.
func UserRoleLT(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldUserRole, v))
}

// UserRoleLTE applies the LTE predicate on the "user_role" field.
func UserRoleLTE(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldUserRole, v))
}

// UserRoleContains applies the Contains predicate on the "user_role" field.
func UserRoleContains(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContains(FieldUserRole, v))
}

// UserRoleHasPrefix applies the HasPrefix predicate on the "user_role" field.
func UserRoleHasPrefix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasPrefix(FieldUserRole, v))
}

// UserRoleHasSuffix applies the HasSuffix predicate on the "user_role" field.
func UserRoleHasSuffix(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldHasSuffix(FieldUserRole, v))
}

// UserRoleEqualFold applies the EqualFold predicate on the "user_role" field.
func UserRoleEqualFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEqualFold(FieldUserRole, v))
}

// UserRoleContainsFold applies the ContainsFold predicate on the "user_role" field.
func UserRoleContainsFold(v string) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldContainsFold(FieldUserRole, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldCreatedAt, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.MCPToken {
	return predicate.MCPToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.MCPToken {
	return predicate.MCPToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.MCPToken {
	return predicate.MCPToken(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MCPToken) predicate.MCPToken {
	return predicate.MCPToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MCPToken) predicate.MCPToken {
	return predicate.MCPToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MCPToken) predicate.MCPToken {
	return predicate.MCPToken(sql.NotPredicates(p))
}
