// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotifyConfigsColumns holds the columns for the "notify_configs" table.
	NotifyConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "send_key", Type: field.TypeString, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "on_success", Type: field.TypeBool, Default: true},
		{Name: "on_failure", Type: field.TypeBool, Default: true},
	}
	// NotifyConfigsTable holds the schema information for the "notify_configs" table.
	NotifyConfigsTable = &schema.Table{
		Name:       "notify_configs",
		Columns:    NotifyConfigsColumns,
		PrimaryKey: []*schema.Column{NotifyConfigsColumns[0]},
	}
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "app_id", Type: field.TypeString},
		{Name: "app_title", Type: field.TypeString, Default: ""},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"resume", "pause"}, Default: "pause"},
		{Name: "week_days", Type: field.TypeJSON},
		{Name: "hour", Type: field.TypeInt, Default: 0},
		{Name: "minute", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "creator", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotifyConfigsTable,
		SchedulesTable,
	}
)

func init() {
}
