// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/mcptoken"
	"apps-scheduler/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MCPTokenUpdate is the builder for updating MCPToken entities.
type MCPTokenUpdate struct {
	config
	hooks    []Hook
	mutation *MCPTokenMutation
}

// Where appends a list predicates to the MCPTokenUpdate builder.
func (_u *MCPTokenUpdate) Where(ps ...predicate.MCPToken) *MCPTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MCPTokenUpdate) SetName(v string) *MCPTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableName(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *MCPTokenUpdate) SetTokenHash(v string) *MCPTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableTokenHash(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *MCPTokenUpdate) SetTokenPrefix(v string) *MCPTokenUpdate {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableTokenPrefix(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MCPTokenUpdate) SetUserID(v string) *MCPTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableUserID(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *MCPTokenUpdate) SetUserRole(v string) *MCPTokenUpdate {
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableUserRole(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *MCPTokenUpdate) SetLastUsedAt(v time.Time) *MCPTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableLastUsedAt(v *time.Time) *MCPTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *MCPTokenUpdate) ClearLastUsedAt() *MCPTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *MCPTokenUpdate) SetRevokedAt(v time.Time) *MCPTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableRevokedAt(v *time.Time) *MCPTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *MCPTokenUpdate) ClearRevokedAt() *MCPTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the MCPTokenMutation object of the builder.
func (_u *MCPTokenUpdate) Mutation() *MCPTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MCPTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MCPTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPTokenUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mcptoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPToken.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := mcptoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := mcptoken.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := mcptoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MCPToken.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcptoken.Table, mcptoken.Columns, sqlgraph.NewFieldSpec(mcptoken.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcptoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(mcptoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(mcptoken.FieldTokenPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mcptoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(mcptoken.FieldUserRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(mcptoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(mcptoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(mcptoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(mcptoken.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcptoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MCPTokenUpdateOne is the builder for updating a single MCPToken entity.
type MCPTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MCPTokenMutation
}

// SetName sets the "name" field.
func (_u *MCPTokenUpdateOne) SetName(v string) *MCPTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableName(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *MCPTokenUpdateOne) SetTokenHash(v string) *MCPTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableTokenHash(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *MCPTokenUpdateOne) SetTokenPrefix(v string) *MCPTokenUpdateOne {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableTokenPrefix(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MCPTokenUpdateOne) SetUserID(v string) *MCPTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableUserID(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *MCPTokenUpdateOne) SetUserRole(v string) *MCPTokenUpdateOne {
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableUserRole(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *MCPTokenUpdateOne) SetLastUsedAt(v time.Time) *MCPTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *MCPTokenUpdateOne) ClearLastUsedAt() *MCPTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *MCPTokenUpdateOne) SetRevokedAt(v time.Time) *MCPTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *MCPTokenUpdateOne) ClearRevokedAt() *MCPTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the MCPTokenMutation object of the builder.
func (_u *MCPTokenUpdateOne) Mutation() *MCPTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the MCPTokenUpdate builder.
func (_u *MCPTokenUpdateOne) Where(ps ...predicate.MCPToken) *MCPTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MCPTokenUpdateOne) Select(field string, fields ...string) *MCPTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MCPToken entity.
func (_u *MCPTokenUpdateOne) Save(ctx context.Context) (*MCPToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPTokenUpdateOne) SaveX(ctx context.Context) *MCPToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MCPTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mcptoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPToken.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := mcptoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := mcptoken.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := mcptoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MCPToken.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPTokenUpdateOne) sqlSave(ctx context.Context) (_node *MCPToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcptoken.Table, mcptoken.Columns, sqlgraph.NewFieldSpec(mcptoken.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MCPToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcptoken.FieldID)
		for _, f := range fields {
			if !mcptoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcptoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcptoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(mcptoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(mcptoken.FieldTokenPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mcptoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(mcptoken.FieldUserRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(mcptoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(mcptoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(mcptoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(mcptoken.FieldRevokedAt, field.TypeTime)
	}
	_node = &MCPToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcptoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
