// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/mcptoken"
	"apps-scheduler/internal/ent/notifyconfig"
	"apps-scheduler/internal/ent/predicate"
	"apps-scheduler/internal/ent/schedule"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMCPToken     = "MCPToken"
	TypeNotifyConfig = "NotifyConfig"
	TypeSchedule     = "Schedule"
)

// MCPTokenMutation represents an operation that mutates the MCPToken nodes in the graph.
type MCPTokenMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	token_hash    *string
	token_prefix  *string
	user_id       *string
	user_role     *string
	created_at    *time.Time
	last_used_at  *time.Time
	revoked_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MCPToken, error)
	predicates    []predicate.MCPToken
}

var _ ent.Mutation = (*MCPTokenMutation)(nil)

// mcptokenOption allows management of the mutation configuration using functional options.
type mcptokenOption func(*MCPTokenMutation)

// newMCPTokenMutation creates new mutation for the MCPToken entity.
func newMCPTokenMutation(c config, op Op, opts ...mcptokenOption) *MCPTokenMutation {
	m := &MCPTokenMutation{
		config:        c,
		op:            op,
		typ:           TypeMCPToken,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMCPTokenID sets the ID field of the mutation.
func withMCPTokenID(id uuid.UUID) mcptokenOption {
	return func(m *MCPTokenMutation) {
		var (
			err   error
			once  sync.Once
			value *MCPToken
		)
		m.oldValue = func(ctx context.Context) (*MCPToken, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MCPToken.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMCPToken sets the old MCPToken of the mutation.
func withMCPToken(node *MCPToken) mcptokenOption {
	return func(m *MCPTokenMutation) {
		m.oldValue = func(context.Context) (*MCPToken, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MCPTokenMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MCPTokenMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of MCPToken entities.
func (m *MCPTokenMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MCPTokenMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MCPTokenMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MCPToken.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *MCPTokenMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *MCPTokenMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *MCPTokenMutation) ResetName() {
	m.name = nil
}

// SetTokenHash sets the "token_hash" field.
func (m *MCPTokenMutation) SetTokenHash(s string) {
	m.token_hash = &s
}

// TokenHash returns the value of the "token_hash" field in the mutation.
func (m *MCPTokenMutation) TokenHash() (r string, exists bool) {
	v := m.token_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldTokenHash returns the old "token_hash" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldTokenHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTokenHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTokenHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTokenHash: %w", err)
	}
	return oldValue.TokenHash, nil
}

// ResetTokenHash resets all changes to the "token_hash" field.
func (m *MCPTokenMutation) ResetTokenHash() {
	m.token_hash = nil
}

// SetTokenPrefix sets the "token_prefix" field.
func (m *MCPTokenMutation) SetTokenPrefix(s string) {
	m.token_prefix = &s
}

// TokenPrefix returns the value of the "token_prefix" field in the mutation.
func (m *MCPTokenMutation) TokenPrefix() (r string, exists bool) {
	v := m.token_prefix
	if v == nil {
		return
	}
	return *v, true
}

// OldTokenPrefix returns the old "token_prefix" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldTokenPrefix(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTokenPrefix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTokenPrefix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTokenPrefix: %w", err)
	}
	return oldValue.TokenPrefix, nil
}

// ResetTokenPrefix resets all changes to the "token_prefix" field.
func (m *MCPTokenMutation) ResetTokenPrefix() {
	m.token_prefix = nil
}

// SetUserID sets the "user_id" field.
func (m *MCPTokenMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *MCPTokenMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *MCPTokenMutation) ResetUserID() {
	m.user_id = nil
}

// SetUserRole sets the "user_role" field.
func (m *MCPTokenMutation) SetUserRole(s string) {
	m.user_role = &s
}

// UserRole returns the value of the "user_role" field in the mutation.
func (m *MCPTokenMutation) UserRole() (r string, exists bool) {
	v := m.user_role
	if v == nil {
		return
	}
	return *v, true
}

// OldUserRole returns the old "user_role" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldUserRole(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserRole is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserRole requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserRole: %w", err)
	}
	return oldValue.UserRole, nil
}

// ResetUserRole resets all changes to the "user_role" field.
func (m *MCPTokenMutation) ResetUserRole() {
	m.user_role = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *MCPTokenMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *MCPTokenMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *MCPTokenMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetLastUsedAt sets the "last_used_at" field.
func (m *MCPTokenMutation) SetLastUsedAt(t time.Time) {
	m.last_used_at = &t
}

// LastUsedAt returns the value of the "last_used_at" field in the mutation.
func (m *MCPTokenMutation) LastUsedAt() (r time.Time, exists bool) {
	v := m.last_used_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastUsedAt returns the old "last_used_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldLastUsedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastUsedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastUsedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastUsedAt: %w", err)
	}
	return oldValue.LastUsedAt, nil
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (m *MCPTokenMutation) ClearLastUsedAt() {
	m.last_used_at = nil
	m.clearedFields[mcptoken.FieldLastUsedAt] = struct{}{}
}

// LastUsedAtCleared returns if the "last_used_at" field was cleared in this mutation.
func (m *MCPTokenMutation) LastUsedAtCleared() bool {
	_, ok := m.clearedFields[mcptoken.FieldLastUsedAt]
	return ok
}

// ResetLastUsedAt resets all changes to the "last_used_at" field.
func (m *MCPTokenMutation) ResetLastUsedAt() {
	m.last_used_at = nil
	delete(m.clearedFields, mcptoken.FieldLastUsedAt)
}

// SetRevokedAt sets the "revoked_at" field.
func (m *MCPTokenMutation) SetRevokedAt(t time.Time) {
	m.revoked_at = &t
}

// RevokedAt returns the value of the "revoked_at" field in the mutation.
func (m *MCPTokenMutation) RevokedAt() (r time.Time, exists bool) {
	v := m.revoked_at
	if v == nil {
		return
	}
	return *v, true
}

// OldRevokedAt returns the old "revoked_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldRevokedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRevokedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRevokedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRevokedAt: %w", err)
	}
	return oldValue.RevokedAt, nil
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (m *MCPTokenMutation) ClearRevokedAt() {
	m.revoked_at = nil
	m.clearedFields[mcptoken.FieldRevokedAt] = struct{}{}
}

// RevokedAtCleared returns if the "revoked_at" field was cleared in this mutation.
func (m *MCPTokenMutation) RevokedAtCleared() bool {
	_, ok := m.clearedFields[mcptoken.FieldRevokedAt]
	return ok
}

// ResetRevokedAt resets all changes to the "revoked_at" field.
func (m *MCPTokenMutation) ResetRevokedAt() {
	m.revoked_at = nil
	delete(m.clearedFields, mcptoken.FieldRevokedAt)
}

// Where appends a list predicates to the MCPTokenMutation builder.
func (m *MCPTokenMutation) Where(ps ...predicate.MCPToken) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MCPTokenMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MCPTokenMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MCPToken, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MCPTokenMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MCPTokenMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MCPToken).
func (m *MCPTokenMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MCPTokenMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.name != nil {
		fields = append(fields, mcptoken.FieldName)
	}
	if m.token_hash != nil {
		fields = append(fields, mcptoken.FieldTokenHash)
	}
	if m.token_prefix != nil {
		fields = append(fields, mcptoken.FieldTokenPrefix)
	}
	if m.user_id != nil {
		fields = append(fields, mcptoken.FieldUserID)
	}
	if m.user_role != nil {
		fields = append(fields, mcptoken.FieldUserRole)
	}
	if m.created_at != nil {
		fields = append(fields, mcptoken.FieldCreatedAt)
	}
	if m.last_used_at != nil {
		fields = append(fields, mcptoken.FieldLastUsedAt)
	}
	if m.revoked_at != nil {
		fields = append(fields, mcptoken.FieldRevokedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MCPTokenMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case mcptoken.FieldName:
		return m.Name()
	case mcptoken.FieldTokenHash:
		return m.TokenHash()
	case mcptoken.FieldTokenPrefix:
		return m.TokenPrefix()
	case mcptoken.FieldUserID:
		return m.UserID()
	case mcptoken.FieldUserRole:
		return m.UserRole()
	case mcptoken.FieldCreatedAt:
		return m.CreatedAt()
	case mcptoken.FieldLastUsedAt:
		return m.LastUsedAt()
	case mcptoken.FieldRevokedAt:
		return m.RevokedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MCPTokenMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case mcptoken.FieldName:
		return m.OldName(ctx)
	case mcptoken.FieldTokenHash:
		return m.OldTokenHash(ctx)
	case mcptoken.FieldTokenPrefix:
		return m.OldTokenPrefix(ctx)
	case mcptoken.FieldUserID:
		return m.OldUserID(ctx)
	case mcptoken.FieldUserRole:
		return m.OldUserRole(ctx)
	case mcptoken.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case mcptoken.FieldLastUsedAt:
		return m.OldLastUsedAt(ctx)
	case mcptoken.FieldRevokedAt:
		return m.OldRevokedAt(ctx)
	}
	return nil, fmt.Errorf("unknown MCPToken field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MCPTokenMutation) SetField(name string, value ent.Value) error {
	switch name {
	case mcptoken.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case mcptoken.FieldTokenHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTokenHash(v)
		return nil
	case mcptoken.FieldTokenPrefix:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTokenPrefix(v)
		return nil
	case mcptoken.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case mcptoken.FieldUserRole:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserRole(v)
		return nil
	case mcptoken.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case mcptoken.FieldLastUsedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastUsedAt(v)
		return nil
	case mcptoken.FieldRevokedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRevokedAt(v)
		return nil
	}
	return fmt.Errorf("unknown MCPToken field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MCPTokenMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MCPTokenMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MCPTokenMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown MCPToken numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MCPTokenMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(mcptoken.FieldLastUsedAt) {
		fields = append(fields, mcptoken.FieldLastUsedAt)
	}
	if m.FieldCleared(mcptoken.FieldRevokedAt) {
		fields = append(fields, mcptoken.FieldRevokedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MCPTokenMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MCPTokenMutation) ClearField(name string) error {
	switch name {
	case mcptoken.FieldLastUsedAt:
		m.ClearLastUsedAt()
		return nil
	case mcptoken.FieldRevokedAt:
		m.ClearRevokedAt()
		return nil
	}
	return fmt.Errorf("unknown MCPToken nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MCPTokenMutation) ResetField(name string) error {
	switch name {
	case mcptoken.FieldName:
		m.ResetName()
		return nil
	case mcptoken.FieldTokenHash:
		m.ResetTokenHash()
		return nil
	case mcptoken.FieldTokenPrefix:
		m.ResetTokenPrefix()
		return nil
	case mcptoken.FieldUserID:
		m.ResetUserID()
		return nil
	case mcptoken.FieldUserRole:
		m.ResetUserRole()
		return nil
	case mcptoken.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case mcptoken.FieldLastUsedAt:
		m.ResetLastUsedAt()
		return nil
	case mcptoken.FieldRevokedAt:
		m.ResetRevokedAt()
		return nil
	}
	return fmt.Errorf("unknown MCPToken field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MCPTokenMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MCPTokenMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MCPTokenMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MCPTokenMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MCPTokenMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MCPTokenMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MCPTokenMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MCPToken unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MCPTokenMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MCPToken edge %s", name)
}

// NotifyConfigMutation represents an operation that mutates the NotifyConfig nodes in the graph.
type NotifyConfigMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user_id       *string
	send_key      *string
	enabled       *bool
	on_success    *bool
	on_failure    *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*NotifyConfig, error)
	predicates    []predicate.NotifyConfig
}

var _ ent.Mutation = (*NotifyConfigMutation)(nil)

// notifyconfigOption allows management of the mutation configuration using functional options.
type notifyconfigOption func(*NotifyConfigMutation)

// newNotifyConfigMutation creates new mutation for the NotifyConfig entity.
func newNotifyConfigMutation(c config, op Op, opts ...notifyconfigOption) *NotifyConfigMutation {
	m := &NotifyConfigMutation{
		config:        c,
		op:            op,
		typ:           TypeNotifyConfig,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotifyConfigID sets the ID field of the mutation.
func withNotifyConfigID(id int) notifyconfigOption {
	return func(m *NotifyConfigMutation) {
		var (
			err   error
			once  sync.Once
			value *NotifyConfig
		)
		m.oldValue = func(ctx context.Context) (*NotifyConfig, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().NotifyConfig.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotifyConfig sets the old NotifyConfig of the mutation.
func withNotifyConfig(node *NotifyConfig) notifyconfigOption {
	return func(m *NotifyConfigMutation) {
		m.oldValue = func(context.Context) (*NotifyConfig, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotifyConfigMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotifyConfigMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of NotifyConfig entities.
func (m *NotifyConfigMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotifyConfigMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotifyConfigMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().NotifyConfig.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *NotifyConfigMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *NotifyConfigMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the NotifyConfig entity.
// If the NotifyConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifyConfigMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *NotifyConfigMutation) ResetUserID() {
	m.user_id = nil
}

// SetSendKey sets the "send_key" field.
func (m *NotifyConfigMutation) SetSendKey(s string) {
	m.send_key = &s
}

// SendKey returns the value of the "send_key" field in the mutation.
func (m *NotifyConfigMutation) SendKey() (r string, exists bool) {
	v := m.send_key
	if v == nil {
		return
	}
	return *v, true
}

// OldSendKey returns the old "send_key" field's value of the NotifyConfig entity.
// If the NotifyConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifyConfigMutation) OldSendKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSendKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSendKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSendKey: %w", err)
	}
	return oldValue.SendKey, nil
}

// ResetSendKey resets all changes to the "send_key" field.
func (m *NotifyConfigMutation) ResetSendKey() {
	m.send_key = nil
}

// SetEnabled sets the "enabled" field.
func (m *NotifyConfigMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *NotifyConfigMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the NotifyConfig entity.
// If the NotifyConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifyConfigMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *NotifyConfigMutation) ResetEnabled() {
	m.enabled = nil
}

// SetOnSuccess sets the "on_success" field.
func (m *NotifyConfigMutation) SetOnSuccess(b bool) {
	m.on_success = &b
}

// OnSuccess returns the value of the "on_success" field in the mutation.
func (m *NotifyConfigMutation) OnSuccess() (r bool, exists bool) {
	v := m.on_success
	if v == nil {
		return
	}
	return *v, true
}

// OldOnSuccess returns the old "on_success" field's value of the NotifyConfig entity.
// If the NotifyConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifyConfigMutation) OldOnSuccess(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOnSuccess is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOnSuccess requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOnSuccess: %w", err)
	}
	return oldValue.OnSuccess, nil
}

// ResetOnSuccess resets all changes to the "on_success" field.
func (m *NotifyConfigMutation) ResetOnSuccess() {
	m.on_success = nil
}

// SetOnFailure sets the "on_failure" field.
func (m *NotifyConfigMutation) SetOnFailure(b bool) {
	m.on_failure = &b
}

// OnFailure returns the value of the "on_failure" field in the mutation.
func (m *NotifyConfigMutation) OnFailure() (r bool, exists bool) {
	v := m.on_failure
	if v == nil {
		return
	}
	return *v, true
}

// OldOnFailure returns the old "on_failure" field's value of the NotifyConfig entity.
// If the NotifyConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifyConfigMutation) OldOnFailure(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOnFailure is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOnFailure requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOnFailure: %w", err)
	}
	return oldValue.OnFailure, nil
}

// ResetOnFailure resets all changes to the "on_failure" field.
func (m *NotifyConfigMutation) ResetOnFailure() {
	m.on_failure = nil
}

// Where appends a list predicates to the NotifyConfigMutation builder.
func (m *NotifyConfigMutation) Where(ps ...predicate.NotifyConfig) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotifyConfigMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotifyConfigMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.NotifyConfig, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotifyConfigMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotifyConfigMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (NotifyConfig).
func (m *NotifyConfigMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotifyConfigMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.user_id != nil {
		fields = append(fields, notifyconfig.FieldUserID)
	}
	if m.send_key != nil {
		fields = append(fields, notifyconfig.FieldSendKey)
	}
	if m.enabled != nil {
		fields = append(fields, notifyconfig.FieldEnabled)
	}
	if m.on_success != nil {
		fields = append(fields, notifyconfig.FieldOnSuccess)
	}
	if m.on_failure != nil {
		fields = append(fields, notifyconfig.FieldOnFailure)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotifyConfigMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notifyconfig.FieldUserID:
		return m.UserID()
	case notifyconfig.FieldSendKey:
		return m.SendKey()
	case notifyconfig.FieldEnabled:
		return m.Enabled()
	case notifyconfig.FieldOnSuccess:
		return m.OnSuccess()
	case notifyconfig.FieldOnFailure:
		return m.OnFailure()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotifyConfigMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notifyconfig.FieldUserID:
		return m.OldUserID(ctx)
	case notifyconfig.FieldSendKey:
		return m.OldSendKey(ctx)
	case notifyconfig.FieldEnabled:
		return m.OldEnabled(ctx)
	case notifyconfig.FieldOnSuccess:
		return m.OldOnSuccess(ctx)
	case notifyconfig.FieldOnFailure:
		return m.OldOnFailure(ctx)
	}
	return nil, fmt.Errorf("unknown NotifyConfig field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotifyConfigMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notifyconfig.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case notifyconfig.FieldSendKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSendKey(v)
		return nil
	case notifyconfig.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case notifyconfig.FieldOnSuccess:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOnSuccess(v)
		return nil
	case notifyconfig.FieldOnFailure:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOnFailure(v)
		return nil
	}
	return fmt.Errorf("unknown NotifyConfig field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotifyConfigMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotifyConfigMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotifyConfigMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown NotifyConfig numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotifyConfigMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotifyConfigMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotifyConfigMutation) ClearField(name string) error {
	return fmt.Errorf("unknown NotifyConfig nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotifyConfigMutation) ResetField(name string) error {
	switch name {
	case notifyconfig.FieldUserID:
		m.ResetUserID()
		return nil
	case notifyconfig.FieldSendKey:
		m.ResetSendKey()
		return nil
	case notifyconfig.FieldEnabled:
		m.ResetEnabled()
		return nil
	case notifyconfig.FieldOnSuccess:
		m.ResetOnSuccess()
		return nil
	case notifyconfig.FieldOnFailure:
		m.ResetOnFailure()
		return nil
	}
	return fmt.Errorf("unknown NotifyConfig field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotifyConfigMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotifyConfigMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotifyConfigMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotifyConfigMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotifyConfigMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotifyConfigMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotifyConfigMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown NotifyConfig unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotifyConfigMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown NotifyConfig edge %s", name)
}

// ScheduleMutation represents an operation that mutates the Schedule nodes in the graph.
type ScheduleMutation struct {
	config
	op                        Op
	typ                       string
	id                        *uuid.UUID
	name                      *string
	app_id                    *string
	app_title                 *string
	operation                 *schedule.Operation
	week_days                 *[]int
	appendweek_days           []int
	hour                      *int
	addhour                   *int
	minute                    *int
	addminute                 *int
	check_interval_minutes    *int
	addcheck_interval_minutes *int
	enabled                   *bool
	creator                   *string
	created_at                *time.Time
	updated_at                *time.Time
	clearedFields             map[string]struct{}
	done                      bool
	oldValue                  func(context.Context) (*Schedule, error)
	predicates                []predicate.Schedule
}

var _ ent.Mutation = (*ScheduleMutation)(nil)

// scheduleOption allows management of the mutation configuration using functional options.
type scheduleOption func(*ScheduleMutation)

// newScheduleMutation creates new mutation for the Schedule entity.
func newScheduleMutation(c config, op Op, opts ...scheduleOption) *ScheduleMutation {
	m := &ScheduleMutation{
		config:        c,
		op:            op,
		typ:           TypeSchedule,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withScheduleID sets the ID field of the mutation.
func withScheduleID(id uuid.UUID) scheduleOption {
	return func(m *ScheduleMutation) {
		var (
			err   error
			once  sync.Once
			value *Schedule
		)
		m.oldValue = func(ctx context.Context) (*Schedule, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Schedule.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSchedule sets the old Schedule of the mutation.
func withSchedule(node *Schedule) scheduleOption {
	return func(m *ScheduleMutation) {
		m.oldValue = func(context.Context) (*Schedule, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ScheduleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ScheduleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Schedule entities.
func (m *ScheduleMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ScheduleMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ScheduleMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Schedule.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ScheduleMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ScheduleMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ScheduleMutation) ResetName() {
	m.name = nil
}

// SetAppID sets the "app_id" field.
func (m *ScheduleMutation) SetAppID(s string) {
	m.app_id = &s
}

// AppID returns the value of the "app_id" field in the mutation.
func (m *ScheduleMutation) AppID() (r string, exists bool) {
	v := m.app_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAppID returns the old "app_id" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldAppID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppID: %w", err)
	}
	return oldValue.AppID, nil
}

// ResetAppID resets all changes to the "app_id" field.
func (m *ScheduleMutation) ResetAppID() {
	m.app_id = nil
}

// SetAppTitle sets the "app_title" field.
func (m *ScheduleMutation) SetAppTitle(s string) {
	m.app_title = &s
}

// AppTitle returns the value of the "app_title" field in the mutation.
func (m *ScheduleMutation) AppTitle() (r string, exists bool) {
	v := m.app_title
	if v == nil {
		return
	}
	return *v, true
}

// OldAppTitle returns the old "app_title" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldAppTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppTitle: %w", err)
	}
	return oldValue.AppTitle, nil
}

// ResetAppTitle resets all changes to the "app_title" field.
func (m *ScheduleMutation) ResetAppTitle() {
	m.app_title = nil
}

// SetOperation sets the "operation" field.
func (m *ScheduleMutation) SetOperation(s schedule.Operation) {
	m.operation = &s
}

// Operation returns the value of the "operation" field in the mutation.
func (m *ScheduleMutation) Operation() (r schedule.Operation, exists bool) {
	v := m.operation
	if v == nil {
		return
	}
	return *v, true
}

// OldOperation returns the old "operation" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldOperation(ctx context.Context) (v schedule.Operation, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOperation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOperation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOperation: %w", err)
	}
	return oldValue.Operation, nil
}

// ResetOperation resets all changes to the "operation" field.
func (m *ScheduleMutation) ResetOperation() {
	m.operation = nil
}

// SetWeekDays sets the "week_days" field.
func (m *ScheduleMutation) SetWeekDays(i []int) {
	m.week_days = &i
	m.appendweek_days = nil
}

// WeekDays returns the value of the "week_days" field in the mutation.
func (m *ScheduleMutation) WeekDays() (r []int, exists bool) {
	v := m.week_days
	if v == nil {
		return
	}
	return *v, true
}

// OldWeekDays returns the old "week_days" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldWeekDays(ctx context.Context) (v []int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWeekDays is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWeekDays requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWeekDays: %w", err)
	}
	return oldValue.WeekDays, nil
}

// AppendWeekDays adds i to the "week_days" field.
func (m *ScheduleMutation) AppendWeekDays(i []int) {
	m.appendweek_days = append(m.appendweek_days, i...)
}

// AppendedWeekDays returns the list of values that were appended to the "week_days" field in this mutation.
func (m *ScheduleMutation) AppendedWeekDays() ([]int, bool) {
	if len(m.appendweek_days) == 0 {
		return nil, false
	}
	return m.appendweek_days, true
}

// ResetWeekDays resets all changes to the "week_days" field.
func (m *ScheduleMutation) ResetWeekDays() {
	m.week_days = nil
	m.appendweek_days = nil
}

// SetHour sets the "hour" field.
func (m *ScheduleMutation) SetHour(i int) {
	m.hour = &i
	m.addhour = nil
}

// Hour returns the value of the "hour" field in the mutation.
func (m *ScheduleMutation) Hour() (r int, exists bool) {
	v := m.hour
	if v == nil {
		return
	}
	return *v, true
}

// OldHour returns the old "hour" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldHour(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHour is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHour requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHour: %w", err)
	}
	return oldValue.Hour, nil
}

// AddHour adds i to the "hour" field.
func (m *ScheduleMutation) AddHour(i int) {
	if m.addhour != nil {
		*m.addhour += i
	} else {
		m.addhour = &i
	}
}

// AddedHour returns the value that was added to the "hour" field in this mutation.
func (m *ScheduleMutation) AddedHour() (r int, exists bool) {
	v := m.addhour
	if v == nil {
		return
	}
	return *v, true
}

// ResetHour resets all changes to the "hour" field.
func (m *ScheduleMutation) ResetHour() {
	m.hour = nil
	m.addhour = nil
}

// SetMinute sets the "minute" field.
func (m *ScheduleMutation) SetMinute(i int) {
	m.minute = &i
	m.addminute = nil
}

// Minute returns the value of the "minute" field in the mutation.
func (m *ScheduleMutation) Minute() (r int, exists bool) {
	v := m.minute
	if v == nil {
		return
	}
	return *v, true
}

// OldMinute returns the old "minute" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldMinute(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMinute is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMinute requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinute: %w", err)
	}
	return oldValue.Minute, nil
}

// AddMinute adds i to the "minute" field.
func (m *ScheduleMutation) AddMinute(i int) {
	if m.addminute != nil {
		*m.addminute += i
	} else {
		m.addminute = &i
	}
}

// AddedMinute returns the value that was added to the "minute" field in this mutation.
func (m *ScheduleMutation) AddedMinute() (r int, exists bool) {
	v := m.addminute
	if v == nil {
		return
	}
	return *v, true
}

// ResetMinute resets all changes to the "minute" field.
func (m *ScheduleMutation) ResetMinute() {
	m.minute = nil
	m.addminute = nil
}

// SetCheckIntervalMinutes sets the "check_interval_minutes" field.
func (m *ScheduleMutation) SetCheckIntervalMinutes(i int) {
	m.check_interval_minutes = &i
	m.addcheck_interval_minutes = nil
}

// CheckIntervalMinutes returns the value of the "check_interval_minutes" field in the mutation.
func (m *ScheduleMutation) CheckIntervalMinutes() (r int, exists bool) {
	v := m.check_interval_minutes
	if v == nil {
		return
	}
	return *v, true
}

// OldCheckIntervalMinutes returns the old "check_interval_minutes" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldCheckIntervalMinutes(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCheckIntervalMinutes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCheckIntervalMinutes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCheckIntervalMinutes: %w", err)
	}
	return oldValue.CheckIntervalMinutes, nil
}

// AddCheckIntervalMinutes adds i to the "check_interval_minutes" field.
func (m *ScheduleMutation) AddCheckIntervalMinutes(i int) {
	if m.addcheck_interval_minutes != nil {
		*m.addcheck_interval_minutes += i
	} else {
		m.addcheck_interval_minutes = &i
	}
}

// AddedCheckIntervalMinutes returns the value that was added to the "check_interval_minutes" field in this mutation.
func (m *ScheduleMutation) AddedCheckIntervalMinutes() (r int, exists bool) {
	v := m.addcheck_interval_minutes
	if v == nil {
		return
	}
	return *v, true
}

// ResetCheckIntervalMinutes resets all changes to the "check_interval_minutes" field.
func (m *ScheduleMutation) ResetCheckIntervalMinutes() {
	m.check_interval_minutes = nil
	m.addcheck_interval_minutes = nil
}

// SetEnabled sets the "enabled" field.
func (m *ScheduleMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *ScheduleMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *ScheduleMutation) ResetEnabled() {
	m.enabled = nil
}

// SetCreator sets the "creator" field.
func (m *ScheduleMutation) SetCreator(s string) {
	m.creator = &s
}

// Creator returns the value of the "creator" field in the mutation.
func (m *ScheduleMutation) Creator() (r string, exists bool) {
	v := m.creator
	if v == nil {
		return
	}
	return *v, true
}

// OldCreator returns the old "creator" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldCreator(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreator is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreator requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreator: %w", err)
	}
	return oldValue.Creator, nil
}

// ResetCreator resets all changes to the "creator" field.
func (m *ScheduleMutation) ResetCreator() {
	m.creator = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ScheduleMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ScheduleMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ScheduleMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ScheduleMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ScheduleMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ScheduleMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the ScheduleMutation builder.
func (m *ScheduleMutation) Where(ps ...predicate.Schedule) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ScheduleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ScheduleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Schedule, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ScheduleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ScheduleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Schedule).
func (m *ScheduleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ScheduleMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.name != nil {
		fields = append(fields, schedule.FieldName)
	}
	if m.app_id != nil {
		fields = append(fields, schedule.FieldAppID)
	}
	if m.app_title != nil {
		fields = append(fields, schedule.FieldAppTitle)
	}
	if m.operation != nil {
		fields = append(fields, schedule.FieldOperation)
	}
	if m.week_days != nil {
		fields = append(fields, schedule.FieldWeekDays)
	}
	if m.hour != nil {
		fields = append(fields, schedule.FieldHour)
	}
	if m.minute != nil {
		fields = append(fields, schedule.FieldMinute)
	}
	if m.check_interval_minutes != nil {
		fields = append(fields, schedule.FieldCheckIntervalMinutes)
	}
	if m.enabled != nil {
		fields = append(fields, schedule.FieldEnabled)
	}
	if m.creator != nil {
		fields = append(fields, schedule.FieldCreator)
	}
	if m.created_at != nil {
		fields = append(fields, schedule.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, schedule.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ScheduleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case schedule.FieldName:
		return m.Name()
	case schedule.FieldAppID:
		return m.AppID()
	case schedule.FieldAppTitle:
		return m.AppTitle()
	case schedule.FieldOperation:
		return m.Operation()
	case schedule.FieldWeekDays:
		return m.WeekDays()
	case schedule.FieldHour:
		return m.Hour()
	case schedule.FieldMinute:
		return m.Minute()
	case schedule.FieldCheckIntervalMinutes:
		return m.CheckIntervalMinutes()
	case schedule.FieldEnabled:
		return m.Enabled()
	case schedule.FieldCreator:
		return m.Creator()
	case schedule.FieldCreatedAt:
		return m.CreatedAt()
	case schedule.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ScheduleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case schedule.FieldName:
		return m.OldName(ctx)
	case schedule.FieldAppID:
		return m.OldAppID(ctx)
	case schedule.FieldAppTitle:
		return m.OldAppTitle(ctx)
	case schedule.FieldOperation:
		return m.OldOperation(ctx)
	case schedule.FieldWeekDays:
		return m.OldWeekDays(ctx)
	case schedule.FieldHour:
		return m.OldHour(ctx)
	case schedule.FieldMinute:
		return m.OldMinute(ctx)
	case schedule.FieldCheckIntervalMinutes:
		return m.OldCheckIntervalMinutes(ctx)
	case schedule.FieldEnabled:
		return m.OldEnabled(ctx)
	case schedule.FieldCreator:
		return m.OldCreator(ctx)
	case schedule.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case schedule.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Schedule field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScheduleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case schedule.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case schedule.FieldAppID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppID(v)
		return nil
	case schedule.FieldAppTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppTitle(v)
		return nil
	case schedule.FieldOperation:
		v, ok := value.(schedule.Operation)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOperation(v)
		return nil
	case schedule.FieldWeekDays:
		v, ok := value.([]int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWeekDays(v)
		return nil
	case schedule.FieldHour:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHour(v)
		return nil
	case schedule.FieldMinute:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinute(v)
		return nil
	case schedule.FieldCheckIntervalMinutes:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCheckIntervalMinutes(v)
		return nil
	case schedule.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case schedule.FieldCreator:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreator(v)
		return nil
	case schedule.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case schedule.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Schedule field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ScheduleMutation) AddedFields() []string {
	var fields []string
	if m.addhour != nil {
		fields = append(fields, schedule.FieldHour)
	}
	if m.addminute != nil {
		fields = append(fields, schedule.FieldMinute)
	}
	if m.addcheck_interval_minutes != nil {
		fields = append(fields, schedule.FieldCheckIntervalMinutes)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ScheduleMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case schedule.FieldHour:
		return m.AddedHour()
	case schedule.FieldMinute:
		return m.AddedMinute()
	case schedule.FieldCheckIntervalMinutes:
		return m.AddedCheckIntervalMinutes()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScheduleMutation) AddField(name string, value ent.Value) error {
	switch name {
	case schedule.FieldHour:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHour(v)
		return nil
	case schedule.FieldMinute:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMinute(v)
		return nil
	case schedule.FieldCheckIntervalMinutes:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCheckIntervalMinutes(v)
		return nil
	}
	return fmt.Errorf("unknown Schedule numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ScheduleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ScheduleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ScheduleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Schedule nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ScheduleMutation) ResetField(name string) error {
	switch name {
	case schedule.FieldName:
		m.ResetName()
		return nil
	case schedule.FieldAppID:
		m.ResetAppID()
		return nil
	case schedule.FieldAppTitle:
		m.ResetAppTitle()
		return nil
	case schedule.FieldOperation:
		m.ResetOperation()
		return nil
	case schedule.FieldWeekDays:
		m.ResetWeekDays()
		return nil
	case schedule.FieldHour:
		m.ResetHour()
		return nil
	case schedule.FieldMinute:
		m.ResetMinute()
		return nil
	case schedule.FieldCheckIntervalMinutes:
		m.ResetCheckIntervalMinutes()
		return nil
	case schedule.FieldEnabled:
		m.ResetEnabled()
		return nil
	case schedule.FieldCreator:
		m.ResetCreator()
		return nil
	case schedule.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case schedule.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Schedule field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ScheduleMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ScheduleMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ScheduleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ScheduleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ScheduleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ScheduleMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ScheduleMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Schedule unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ScheduleMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Schedule edge %s", name)
}
