// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/notifyconfig"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// NotifyConfig is the model entity for the NotifyConfig schema.
type NotifyConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// SendKey holds the value of the "send_key" field.
	SendKey string `json:"send_key,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// OnSuccess holds the value of the "on_success" field.
	OnSuccess bool `json:"on_success,omitempty"`
	// OnFailure holds the value of the "on_failure" field.
	OnFailure    bool `json:"on_failure,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotifyConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notifyconfig.FieldEnabled, notifyconfig.FieldOnSuccess, notifyconfig.FieldOnFailure:
			values[i] = new(sql.NullBool)
		case notifyconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case notifyconfig.FieldUserID, notifyconfig.FieldSendKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotifyConfig fields.
func (_m *NotifyConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notifyconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case notifyconfig.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case notifyconfig.FieldSendKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field send_key", values[i])
			} else if value.Valid {
				_m.SendKey = value.String
			}
		case notifyconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case notifyconfig.FieldOnSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field on_success", values[i])
			} else if value.Valid {
				_m.OnSuccess = value.Bool
			}
		case notifyconfig.FieldOnFailure:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field on_failure", values[i])
			} else if value.Valid {
				_m.OnFailure = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotifyConfig.
// This includes values selected through modifiers, order, etc.
func (_m *NotifyConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotifyConfig.
// Note that you need to call NotifyConfig.Unwrap() before calling this method if this NotifyConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotifyConfig) Update() *NotifyConfigUpdateOne {
	return NewNotifyConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotifyConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotifyConfig) Unwrap() *NotifyConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotifyConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotifyConfig) String() string {
	var builder strings.Builder
	builder.WriteString("NotifyConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("send_key=")
	builder.WriteString(_m.SendKey)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("on_success=")
	builder.WriteString(fmt.Sprintf("%v", _m.OnSuccess))
	builder.WriteString(", ")
	builder.WriteString("on_failure=")
	builder.WriteString(fmt.Sprintf("%v", _m.OnFailure))
	builder.WriteByte(')')
	return builder.String()
}

// NotifyConfigs is a parsable slice of NotifyConfig.
type NotifyConfigs []*NotifyConfig
