// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/notifyconfig"
	"apps-scheduler/internal/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotifyConfigDelete is the builder for deleting a NotifyConfig entity.
type NotifyConfigDelete struct {
	config
	hooks    []Hook
	mutation *NotifyConfigMutation
}

// Where appends a list predicates to the NotifyConfigDelete builder.
func (_d *NotifyConfigDelete) Where(ps ...predicate.NotifyConfig) *NotifyConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NotifyConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotifyConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NotifyConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notifyconfig.Table, sqlgraph.NewFieldSpec(notifyconfig.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NotifyConfigDeleteOne is the builder for deleting a single NotifyConfig entity.
type NotifyConfigDeleteOne struct {
	_d *NotifyConfigDelete
}

// Where appends a list predicates to the NotifyConfigDelete builder.
func (_d *NotifyConfigDeleteOne) Where(ps ...predicate.NotifyConfig) *NotifyConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NotifyConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notifyconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotifyConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
