// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/notifyconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotifyConfigCreate is the builder for creating a NotifyConfig entity.
type NotifyConfigCreate struct {
	config
	mutation *NotifyConfigMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *NotifyConfigCreate) SetUserID(v string) *NotifyConfigCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSendKey sets the "send_key" field.
func (_c *NotifyConfigCreate) SetSendKey(v string) *NotifyConfigCreate {
	_c.mutation.SetSendKey(v)
	return _c
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (_c *NotifyConfigCreate) SetNillableSendKey(v *string) *NotifyConfigCreate {
	if v != nil {
		_c.SetSendKey(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotifyConfigCreate) SetEnabled(v bool) *NotifyConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotifyConfigCreate) SetNillableEnabled(v *bool) *NotifyConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetOnSuccess sets the "on_success" field.
func (_c *NotifyConfigCreate) SetOnSuccess(v bool) *NotifyConfigCreate {
	_c.mutation.SetOnSuccess(v)
	return _c
}

// SetNillableOnSuccess sets the "on_success" field if the given value is not nil.
func (_c *NotifyConfigCreate) SetNillableOnSuccess(v *bool) *NotifyConfigCreate {
	if v != nil {
		_c.SetOnSuccess(*v)
	}
	return _c
}

// SetOnFailure sets the "on_failure" field.
func (_c *NotifyConfigCreate) SetOnFailure(v bool) *NotifyConfigCreate {
	_c.mutation.SetOnFailure(v)
	return _c
}

// SetNillableOnFailure sets the "on_failure" field if the given value is not nil.
func (_c *NotifyConfigCreate) SetNillableOnFailure(v *bool) *NotifyConfigCreate {
	if v != nil {
		_c.SetOnFailure(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotifyConfigCreate) SetID(v int) *NotifyConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotifyConfigMutation object of the builder.
func (_c *NotifyConfigCreate) Mutation() *NotifyConfigMutation {
	return _c.mutation
}

// Save creates the NotifyConfig in the database.
func (_c *NotifyConfigCreate) Save(ctx context.Context) (*NotifyConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotifyConfigCreate) SaveX(ctx context.Context) *NotifyConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotifyConfigCreate) defaults() {
	if _, ok := _c.mutation.SendKey(); !ok {
		v := notifyconfig.DefaultSendKey
		_c.mutation.SetSendKey(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notifyconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.OnSuccess(); !ok {
		v := notifyconfig.DefaultOnSuccess
		_c.mutation.SetOnSuccess(v)
	}
	if _, ok := _c.mutation.OnFailure(); !ok {
		v := notifyconfig.DefaultOnFailure
		_c.mutation.SetOnFailure(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotifyConfigCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotifyConfig.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := notifyconfig.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "NotifyConfig.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SendKey(); !ok {
		return &ValidationError{Name: "send_key", err: errors.New(`ent: missing required field "NotifyConfig.send_key"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotifyConfig.enabled"`)}
	}
	if _, ok := _c.mutation.OnSuccess(); !ok {
		return &ValidationError{Name: "on_success", err: errors.New(`ent: missing required field "NotifyConfig.on_success"`)}
	}
	if _, ok := _c.mutation.OnFailure(); !ok {
		return &ValidationError{Name: "on_failure", err: errors.New(`ent: missing required field "NotifyConfig.on_failure"`)}
	}
	return nil
}

func (_c *NotifyConfigCreate) sqlSave(ctx context.Context) (*NotifyConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotifyConfigCreate) createSpec() (*NotifyConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &NotifyConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notifyconfig.Table, sqlgraph.NewFieldSpec(notifyconfig.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(notifyconfig.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.SendKey(); ok {
		_spec.SetField(notifyconfig.FieldSendKey, field.TypeString, value)
		_node.SendKey = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notifyconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.OnSuccess(); ok {
		_spec.SetField(notifyconfig.FieldOnSuccess, field.TypeBool, value)
		_node.OnSuccess = value
	}
	if value, ok := _c.mutation.OnFailure(); ok {
		_spec.SetField(notifyconfig.FieldOnFailure, field.TypeBool, value)
		_node.OnFailure = value
	}
	return _node, _spec
}

// NotifyConfigCreateBulk is the builder for creating many NotifyConfig entities in bulk.
type NotifyConfigCreateBulk struct {
	config
	err      error
	builders []*NotifyConfigCreate
}

// Save creates the NotifyConfig entities in the database.
func (_c *NotifyConfigCreateBulk) Save(ctx context.Context) ([]*NotifyConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotifyConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotifyConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotifyConfigCreateBulk) SaveX(ctx context.Context) []*NotifyConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
