// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/notifyconfig"
	"apps-scheduler/internal/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotifyConfigUpdate is the builder for updating NotifyConfig entities.
type NotifyConfigUpdate struct {
	config
	hooks    []Hook
	mutation *NotifyConfigMutation
}

// Where appends a list predicates to the NotifyConfigUpdate builder.
func (_u *NotifyConfigUpdate) Where(ps ...predicate.NotifyConfig) *NotifyConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotifyConfigUpdate) SetUserID(v string) *NotifyConfigUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotifyConfigUpdate) SetNillableUserID(v *string) *NotifyConfigUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSendKey sets the "send_key" field.
func (_u *NotifyConfigUpdate) SetSendKey(v string) *NotifyConfigUpdate {
	_u.mutation.SetSendKey(v)
	return _u
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (_u *NotifyConfigUpdate) SetNillableSendKey(v *string) *NotifyConfigUpdate {
	if v != nil {
		_u.SetSendKey(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifyConfigUpdate) SetEnabled(v bool) *NotifyConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifyConfigUpdate) SetNillableEnabled(v *bool) *NotifyConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetOnSuccess sets the "on_success" field.
func (_u *NotifyConfigUpdate) SetOnSuccess(v bool) *NotifyConfigUpdate {
	_u.mutation.SetOnSuccess(v)
	return _u
}

// SetNillableOnSuccess sets the "on_success" field if the given value is not nil.
func (_u *NotifyConfigUpdate) SetNillableOnSuccess(v *bool) *NotifyConfigUpdate {
	if v != nil {
		_u.SetOnSuccess(*v)
	}
	return _u
}

// SetOnFailure sets the "on_failure" field.
func (_u *NotifyConfigUpdate) SetOnFailure(v bool) *NotifyConfigUpdate {
	_u.mutation.SetOnFailure(v)
	return _u
}

// SetNillableOnFailure sets the "on_failure" field if the given value is not nil.
func (_u *NotifyConfigUpdate) SetNillableOnFailure(v *bool) *NotifyConfigUpdate {
	if v != nil {
		_u.SetOnFailure(*v)
	}
	return _u
}

// Mutation returns the NotifyConfigMutation object of the builder.
func (_u *NotifyConfigUpdate) Mutation() *NotifyConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotifyConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifyConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotifyConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifyConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifyConfigUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := notifyconfig.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "NotifyConfig.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NotifyConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifyconfig.Table, notifyconfig.Columns, sqlgraph.NewFieldSpec(notifyconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notifyconfig.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendKey(); ok {
		_spec.SetField(notifyconfig.FieldSendKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifyconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OnSuccess(); ok {
		_spec.SetField(notifyconfig.FieldOnSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OnFailure(); ok {
		_spec.SetField(notifyconfig.FieldOnFailure, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifyconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotifyConfigUpdateOne is the builder for updating a single NotifyConfig entity.
type NotifyConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotifyConfigMutation
}

// SetUserID sets the "user_id" field.
func (_u *NotifyConfigUpdateOne) SetUserID(v string) *NotifyConfigUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotifyConfigUpdateOne) SetNillableUserID(v *string) *NotifyConfigUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSendKey sets the "send_key" field.
func (_u *NotifyConfigUpdateOne) SetSendKey(v string) *NotifyConfigUpdateOne {
	_u.mutation.SetSendKey(v)
	return _u
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (_u *NotifyConfigUpdateOne) SetNillableSendKey(v *string) *NotifyConfigUpdateOne {
	if v != nil {
		_u.SetSendKey(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifyConfigUpdateOne) SetEnabled(v bool) *NotifyConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifyConfigUpdateOne) SetNillableEnabled(v *bool) *NotifyConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetOnSuccess sets the "on_success" field.
func (_u *NotifyConfigUpdateOne) SetOnSuccess(v bool) *NotifyConfigUpdateOne {
	_u.mutation.SetOnSuccess(v)
	return _u
}

// SetNillableOnSuccess sets the "on_success" field if the given value is not nil.
func (_u *NotifyConfigUpdateOne) SetNillableOnSuccess(v *bool) *NotifyConfigUpdateOne {
	if v != nil {
		_u.SetOnSuccess(*v)
	}
	return _u
}

// SetOnFailure sets the "on_failure" field.
func (_u *NotifyConfigUpdateOne) SetOnFailure(v bool) *NotifyConfigUpdateOne {
	_u.mutation.SetOnFailure(v)
	return _u
}

// SetNillableOnFailure sets the "on_failure" field if the given value is not nil.
func (_u *NotifyConfigUpdateOne) SetNillableOnFailure(v *bool) *NotifyConfigUpdateOne {
	if v != nil {
		_u.SetOnFailure(*v)
	}
	return _u
}

// Mutation returns the NotifyConfigMutation object of the builder.
func (_u *NotifyConfigUpdateOne) Mutation() *NotifyConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotifyConfigUpdate builder.
func (_u *NotifyConfigUpdateOne) Where(ps ...predicate.NotifyConfig) *NotifyConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotifyConfigUpdateOne) Select(field string, fields ...string) *NotifyConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotifyConfig entity.
func (_u *NotifyConfigUpdateOne) Save(ctx context.Context) (*NotifyConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifyConfigUpdateOne) SaveX(ctx context.Context) *NotifyConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotifyConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifyConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifyConfigUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := notifyconfig.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "NotifyConfig.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NotifyConfigUpdateOne) sqlSave(ctx context.Context) (_node *NotifyConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifyconfig.Table, notifyconfig.Columns, sqlgraph.NewFieldSpec(notifyconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotifyConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifyconfig.FieldID)
		for _, f := range fields {
			if !notifyconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notifyconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notifyconfig.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendKey(); ok {
		_spec.SetField(notifyconfig.FieldSendKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifyconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OnSuccess(); ok {
		_spec.SetField(notifyconfig.FieldOnSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OnFailure(); ok {
		_spec.SetField(notifyconfig.FieldOnFailure, field.TypeBool, value)
	}
	_node = &NotifyConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifyconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
