// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apps-scheduler/internal/ent/notifyconfig"
	"apps-scheduler/internal/ent/schedule"
	"apps-scheduler/internal/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	notifyconfigFields := schema.NotifyConfig{}.Fields()
	_ = notifyconfigFields
	// notifyconfigDescUserID is the schema descriptor for user_id field.
	notifyconfigDescUserID := notifyconfigFields[1].Descriptor()
	// notifyconfig.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	notifyconfig.UserIDValidator = notifyconfigDescUserID.Validators[0].(func(string) error)
	// notifyconfigDescSendKey is the schema descriptor for send_key field.
	notifyconfigDescSendKey := notifyconfigFields[2].Descriptor()
	// notifyconfig.DefaultSendKey holds the default value on creation for the send_key field.
	notifyconfig.DefaultSendKey = notifyconfigDescSendKey.Default.(string)
	// notifyconfigDescEnabled is the schema descriptor for enabled field.
	notifyconfigDescEnabled := notifyconfigFields[3].Descriptor()
	// notifyconfig.DefaultEnabled holds the default value on creation for the enabled field.
	notifyconfig.DefaultEnabled = notifyconfigDescEnabled.Default.(bool)
	// notifyconfigDescOnSuccess is the schema descriptor for on_success field.
	notifyconfigDescOnSuccess := notifyconfigFields[4].Descriptor()
	// notifyconfig.DefaultOnSuccess holds the default value on creation for the on_success field.
	notifyconfig.DefaultOnSuccess = notifyconfigDescOnSuccess.Default.(bool)
	// notifyconfigDescOnFailure is the schema descriptor for on_failure field.
	notifyconfigDescOnFailure := notifyconfigFields[5].Descriptor()
	// notifyconfig.DefaultOnFailure holds the default value on creation for the on_failure field.
	notifyconfig.DefaultOnFailure = notifyconfigDescOnFailure.Default.(bool)
	scheduleFields := schema.Schedule{}.Fields()
	_ = scheduleFields
	// scheduleDescName is the schema descriptor for name field.
	scheduleDescName := scheduleFields[1].Descriptor()
	// schedule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	schedule.NameValidator = scheduleDescName.Validators[0].(func(string) error)
	// scheduleDescAppID is the schema descriptor for app_id field.
	scheduleDescAppID := scheduleFields[2].Descriptor()
	// schedule.AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	schedule.AppIDValidator = scheduleDescAppID.Validators[0].(func(string) error)
	// scheduleDescAppTitle is the schema descriptor for app_title field.
	scheduleDescAppTitle := scheduleFields[3].Descriptor()
	// schedule.DefaultAppTitle holds the default value on creation for the app_title field.
	schedule.DefaultAppTitle = scheduleDescAppTitle.Default.(string)
	// scheduleDescWeekDays is the schema descriptor for week_days field.
	scheduleDescWeekDays := scheduleFields[5].Descriptor()
	// schedule.DefaultWeekDays holds the default value on creation for the week_days field.
	schedule.DefaultWeekDays = scheduleDescWeekDays.Default.([]int)
	// scheduleDescHour is the schema descriptor for hour field.
	scheduleDescHour := scheduleFields[6].Descriptor()
	// schedule.DefaultHour holds the default value on creation for the hour field.
	schedule.DefaultHour = scheduleDescHour.Default.(int)
	// schedule.HourValidator is a validator for the "hour" field. It is called by the builders before save.
	schedule.HourValidator = func() func(int) error {
		validators := scheduleDescHour.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(hour int) error {
			for _, fn := range fns {
				if err := fn(hour); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// scheduleDescMinute is the schema descriptor for minute field.
	scheduleDescMinute := scheduleFields[7].Descriptor()
	// schedule.DefaultMinute holds the default value on creation for the minute field.
	schedule.DefaultMinute = scheduleDescMinute.Default.(int)
	// schedule.MinuteValidator is a validator for the "minute" field. It is called by the builders before save.
	schedule.MinuteValidator = func() func(int) error {
		validators := scheduleDescMinute.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(minute int) error {
			for _, fn := range fns {
				if err := fn(minute); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// scheduleDescEnabled is the schema descriptor for enabled field.
	scheduleDescEnabled := scheduleFields[8].Descriptor()
	// schedule.DefaultEnabled holds the default value on creation for the enabled field.
	schedule.DefaultEnabled = scheduleDescEnabled.Default.(bool)
	// scheduleDescCreatedAt is the schema descriptor for created_at field.
	scheduleDescCreatedAt := scheduleFields[10].Descriptor()
	// schedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedule.DefaultCreatedAt = scheduleDescCreatedAt.Default.(func() time.Time)
	// scheduleDescUpdatedAt is the schema descriptor for updated_at field.
	scheduleDescUpdatedAt := scheduleFields[11].Descriptor()
	// schedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedule.DefaultUpdatedAt = scheduleDescUpdatedAt.Default.(func() time.Time)
	// schedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedule.UpdateDefaultUpdatedAt = scheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scheduleDescID is the schema descriptor for id field.
	scheduleDescID := scheduleFields[0].Descriptor()
	// schedule.DefaultID holds the default value on creation for the id field.
	schedule.DefaultID = scheduleDescID.Default.(func() uuid.UUID)
}
