// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MCPToken is the predicate function for mcptoken builders.
type MCPToken func(*sql.Selector)

// NotifyConfig is the predicate function for notifyconfig builders.
type NotifyConfig func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)
