// Code generated by ent, DO NOT EDIT.

package notifyconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the notifyconfig type in the database.
	Label = "notify_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSendKey holds the string denoting the send_key field in the database.
	FieldSendKey = "send_key"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldOnSuccess holds the string denoting the on_success field in the database.
	FieldOnSuccess = "on_success"
	// FieldOnFailure holds the string denoting the on_failure field in the database.
	FieldOnFailure = "on_failure"
	// Table holds the table name of the notifyconfig in the database.
	Table = "notify_configs"
)

// Columns holds all SQL columns for notifyconfig fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldSendKey,
	FieldEnabled,
	FieldOnSuccess,
	FieldOnFailure,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// DefaultSendKey holds the default value on creation for the "send_key" field.
	DefaultSendKey string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultOnSuccess holds the default value on creation for the "on_success" field.
	DefaultOnSuccess bool
	// DefaultOnFailure holds the default value on creation for the "on_failure" field.
	DefaultOnFailure bool
)

// OrderOption defines the ordering options for the NotifyConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySendKey orders the results by the send_key field.
func BySendKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSendKey, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByOnSuccess orders the results by the on_success field.
func ByOnSuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnSuccess, opts...).ToFunc()
}

// ByOnFailure orders the results by the on_failure field.
func ByOnFailure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnFailure, opts...).ToFunc()
}
