// Code generated by ent, DO NOT EDIT.

package notifyconfig

import (
	"apps-scheduler/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldUserID, v))
}

// SendKey applies equality check predicate on the "send_key" field. It's identical to SendKeyEQ.
func SendKey(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldSendKey, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldEnabled, v))
}

// OnSuccess applies equality check predicate on the "on_success" field. It's identical to OnSuccessEQ.
func OnSuccess(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldOnSuccess, v))
}

// OnFailure applies equality check predicate on the "on_failure" field. It's identical to OnFailureEQ.
func OnFailure(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldOnFailure, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldContainsFold(FieldUserID, v))
}

// SendKeyEQ applies the EQ predicate on the "send_key" field.
func SendKeyEQ(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldSendKey, v))
}

// SendKeyNEQ applies the NEQ predicate on the "send_key" field.
func SendKeyNEQ(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNEQ(FieldSendKey, v))
}

// SendKeyIn applies the In predicate on the "send_key" field.
func SendKeyIn(vs ...string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldIn(FieldSendKey, vs...))
}

// SendKeyNotIn applies the NotIn predicate on the "send_key" field.
func SendKeyNotIn(vs ...string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNotIn(FieldSendKey, vs...))
}

// SendKeyGT applies the GT predicate on the "send_key" field.
func SendKeyGT(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldGT(FieldSendKey, v))
}

// SendKeyGTE applies the GTE predicate on the "send_key" field.
func SendKeyGTE(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldGTE(FieldSendKey, v))
}

// SendKeyLT applies the LT predicate on the "send_key" field.
func SendKeyLT(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldLT(FieldSendKey, v))
}

// SendKeyLTE applies the LTE predicate on the "send_key" field.
func SendKeyLTE(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldLTE(FieldSendKey, v))
}

// SendKeyContains applies the Contains predicate on the "send_key" field.
func SendKeyContains(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldContains(FieldSendKey, v))
}

// SendKeyHasPrefix applies the HasPrefix predicate on the "send_key" field.
func SendKeyHasPrefix(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldHasPrefix(FieldSendKey, v))
}

// SendKeyHasSuffix applies the HasSuffix predicate on the "send_key" field.
func SendKeyHasSuffix(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldHasSuffix(FieldSendKey, v))
}

// SendKeyEqualFold applies the EqualFold predicate on the "send_key" field.
func SendKeyEqualFold(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEqualFold(FieldSendKey, v))
}

// SendKeyContainsFold applies the ContainsFold predicate on the "send_key" field.
func SendKeyContainsFold(v string) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldContainsFold(FieldSendKey, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNEQ(FieldEnabled, v))
}

// OnSuccessEQ applies the EQ predicate on the "on_success" field.
func OnSuccessEQ(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldOnSuccess, v))
}

// OnSuccessNEQ applies the NEQ predicate on the "on_success" field.
func OnSuccessNEQ(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNEQ(FieldOnSuccess, v))
}

// OnFailureEQ applies the EQ predicate on the "on_failure" field.
func OnFailureEQ(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldEQ(FieldOnFailure, v))
}

// OnFailureNEQ applies the NEQ predicate on the "on_failure" field.
func OnFailureNEQ(v bool) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.FieldNEQ(FieldOnFailure, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotifyConfig) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotifyConfig) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotifyConfig) predicate.NotifyConfig {
	return predicate.NotifyConfig(sql.NotPredicates(p))
}
