// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the schedule type in the database.
	Label = "schedule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldAppTitle holds the string denoting the app_title field in the database.
	FieldAppTitle = "app_title"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldWeekDays holds the string denoting the week_days field in the database.
	FieldWeekDays = "week_days"
	// FieldHour holds the string denoting the hour field in the database.
	FieldHour = "hour"
	// FieldMinute holds the string denoting the minute field in the database.
	FieldMinute = "minute"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the schedule in the database.
	Table = "schedules"
)

// Columns holds all SQL columns for schedule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAppID,
	FieldAppTitle,
	FieldOperation,
	FieldWeekDays,
	FieldHour,
	FieldMinute,
	FieldEnabled,
	FieldCreator,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	AppIDValidator func(string) error
	// DefaultAppTitle holds the default value on creation for the "app_title" field.
	DefaultAppTitle string
	// DefaultWeekDays holds the default value on creation for the "week_days" field.
	DefaultWeekDays []int
	// DefaultHour holds the default value on creation for the "hour" field.
	DefaultHour int
	// HourValidator is a validator for the "hour" field. It is called by the builders before save.
	HourValidator func(int) error
	// DefaultMinute holds the default value on creation for the "minute" field.
	DefaultMinute int
	// MinuteValidator is a validator for the "minute" field. It is called by the builders before save.
	MinuteValidator func(int) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Operation defines the type for the "operation" enum field.
type Operation string

// OperationPause is the default value of the Operation enum.
const DefaultOperation = OperationPause

// Operation values.
const (
	OperationResume Operation = "resume"
	OperationPause  Operation = "pause"
)

func (o Operation) String() string {
	return string(o)
}

// OperationValidator is a validator for the "operation" field enum values. It is called by the builders before save.
func OperationValidator(o Operation) error {
	switch o {
	case OperationResume, OperationPause:
		return nil
	default:
		return fmt.Errorf("schedule: invalid enum value for operation field: %q", o)
	}
}

// OrderOption defines the ordering options for the Schedule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByAppTitle orders the results by the app_title field.
func ByAppTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppTitle, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByHour orders the results by the hour field.
func ByHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHour, opts...).ToFunc()
}

// ByMinute orders the results by the minute field.
func ByMinute(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinute, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreator orders the results by the creator field.
func ByCreator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreator, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
